// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiAdmin.Data;

#nullable disable

namespace WebApiAdmin.Migrations
{
    [DbContext(typeof(WebApiAdminContext))]
    partial class WebApiAdminContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiAdmin.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Recursos Humanos de la Matriz",
                            DepartmentName = "MT_RH",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 2,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Operaciones de la Matriz",
                            DepartmentName = "MT_OP",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 3,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Contabilidad y Finanzas de la Matriz",
                            DepartmentName = "MT_CF",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 4,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Marketing de la Matriz",
                            DepartmentName = "MT_MK",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 5,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Recursos Humanos de la Sucursal 1",
                            DepartmentName = "S1_RH",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 6,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Operaciones de la Sucursal 1",
                            DepartmentName = "S1_OP",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 7,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Contabilidad y Finanzas de la Sucursal 1",
                            DepartmentName = "S1_CF",
                            IsActive = true
                        },
                        new
                        {
                            DepartmentId = 8,
                            CreatedAt = new DateOnly(2025, 3, 11),
                            DepartmentDescription = "Marketing de la Sucursal 1",
                            DepartmentName = "S1_MK",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("WebApiAdmin.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            DateTime = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleDescription = "Rol de Administrador",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleId = 2,
                            DateTime = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoleDescription = "Rol de Empleado",
                            RoleName = "Employee"
                        });
                });

            modelBuilder.Entity("WebApiAdmin.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Matriz 1 administrador",
                            City = "Colima",
                            Country = "México",
                            CreatedAt = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 3, 11),
                            DepartmentId = 1,
                            Email = "admin@admin.com",
                            IsActive = true,
                            LastName = "Administrador",
                            Name = "Admin",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Sucursal 1 administrador",
                            City = "Manzanillo",
                            Country = "México",
                            CreatedAt = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2000, 6, 22),
                            DepartmentId = 5,
                            Email = "empleado1@empleados.com",
                            IsActive = true,
                            LastName = "Empleado de sucursal",
                            Name = "Empleado 1",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("WebApiAdmin.Models.User", b =>
                {
                    b.HasOne("WebApiAdmin.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiAdmin.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApiAdmin.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApiAdmin.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
